# 03 - Build Processed Dataset

This notebook READS the raw CSV and WRITES the analytical dataset (`data/processed/loans_clean.parquet`).
It implements `docs/cleaning_decisions.md` line by line. If anything here diverges from the document,
the notebook stops (assert) and flags it — it does not decide on its own.

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)

RAW_PATH = Path('..') / 'data' / 'raw' / 'accepted_2007_to_2018Q4.csv'
PROCESSED_DIR = Path('..') / 'data' / 'processed'
CHUNK_SIZE = 50000
CUTOFF_36 = pd.Timestamp('2015-12-01')
CUTOFF_60 = pd.Timestamp('2013-12-01')


## 1. Approved population

loan_status in {Fully Paid, Charged Off}; 36m term with issue_d up to Dec/2015; 60m term up to
Dec/2013. Expected N = 673,553. If it does not match, the assert stops the notebook.

In [2]:
pop_chunks = []
n_total_file = 0
for chunk in pd.read_csv(RAW_PATH, chunksize=CHUNK_SIZE, low_memory=False):
    n_total_file += len(chunk)
    status_ok = chunk['loan_status'].isin(['Fully Paid', 'Charged Off'])
    issue_dt = pd.to_datetime(chunk['issue_d'], format='%b-%Y', errors='coerce')
    term_clean = chunk['term'].str.strip()
    is_36 = term_clean == '36 months'
    is_60 = term_clean == '60 months'
    mature = (is_36 & issue_dt.notna() & (issue_dt <= CUTOFF_36)) | (is_60 & issue_dt.notna() & (issue_dt <= CUTOFF_60))
    pop_mask = status_ok & mature
    if pop_mask.any():
        pop_chunks.append(chunk.loc[pop_mask].copy())

df = pd.concat(pop_chunks, ignore_index=True)
del pop_chunks

print(f'Rows read from the whole file: {n_total_file:,}')
print(f'Population N: {len(df):,}')
assert len(df) == 673553, f'Unexpected N: {len(df)} (expected 673553) - STOPPING, diverges from the contract.'
print('N matches the expected value (673,553). Proceeding.')


Rows read from the whole file: 2,260,701
Population N: 673,553
N matches the expected value (673,553). Proceeding.


## 2. Target

In [3]:
df['target'] = df['loan_status'].map({'Fully Paid': 0, 'Charged Off': 1})
print('target created. Distribution:')
print(df['target'].value_counts())
print(f'Default rate: {df["target"].mean() * 100:.4f}%')


target created. Distribution:
target
0    573768
1     99785
Name: count, dtype: int64
Default rate: 14.8147%


## 3. Removal of the 5 rows with dti > 100 (error, not a legitimate outlier)

In [4]:
n_before = len(df)
df = df.loc[~(df['dti'] > 100)].reset_index(drop=True)
n_removed = n_before - len(df)
print(f'Rows removed (dti > 100): {n_removed} (expected: 5)')
assert n_removed == 5, f'Expected to remove 5 rows, removed {n_removed} - STOPPING, diverges from the contract.'
print(f'New N: {len(df):,}')


Rows removed (dti > 100): 5 (expected: 5)
New N: 673,548


## Mechanical transformations (documented in cleaning_decisions.md)

Dates to real datetime; `term` to months (a number, keeping the name — it is EVAL_ONLY and has to
be numeric for the financial-outcome calculation); `emp_length` parsed into
`emp_length_anos` (years; new column, the original string is dropped as redundant); low-cardinality
categoricals get strip+lower (cardinality does not change, already documented).

In [5]:
date_cols = ['issue_d', 'earliest_cr_line']
for c in date_cols:
    df[c] = pd.to_datetime(df[c], format='%b-%Y', errors='coerce')
print('Dates converted:', date_cols)

df['term'] = df['term'].str.strip().str.extract(r'(\d+)').astype(float)
print('term converted to numeric (months). Unique values:', sorted(df['term'].dropna().unique()))

def parse_emp_length(v):
    if pd.isna(v):
        return np.nan
    v = v.strip()
    if v == '< 1 year':
        return 0.0
    if v == '10+ years':
        return 10.0
    digits = ''.join(ch for ch in v if ch.isdigit())
    return float(digits) if digits else np.nan

df['emp_length_anos'] = df['emp_length'].apply(parse_emp_length)
print('emp_length_anos created. Unique values:', sorted(df['emp_length_anos'].dropna().unique()))

low_card_cols = ['grade', 'sub_grade', 'home_ownership', 'purpose', 'verification_status',
                  'addr_state', 'initial_list_status', 'application_type']
for c in low_card_cols:
    before_card = df[c].nunique(dropna=True)
    df[c] = df[c].str.strip().str.lower()
    after_card = df[c].nunique(dropna=True)
    print(f'{c}: cardinality before={before_card} after={after_card}')


Dates converted: ['issue_d', 'earliest_cr_line']


term converted to numeric (months). Unique values: [np.float64(36.0), np.float64(60.0)]


emp_length_anos created. Unique values: [np.float64(0.0), np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0), np.float64(10.0)]
grade: cardinality before=7 after=7
sub_grade: cardinality before=35 after=35
home_ownership: cardinality before=6 after=6


purpose: cardinality before=14 after=14
verification_status: cardinality before=3 after=3
addr_state: cardinality before=51 after=51
initial_list_status: cardinality before=2 after=2


application_type: cardinality before=2 after=2


## 4. Column drops (with an explicit reason)

Before dropping, the full list is printed: column -> reason.

In [6]:
drop_reasons = {}

for c in ['id', 'member_id', 'url']:
    drop_reasons[c] = 'Family A - identifier'

family_B_original = [
    'out_prncp', 'out_prncp_inv',
    'total_pymnt', 'total_pymnt_inv', 'total_rec_int', 'total_rec_late_fee',
    'recoveries', 'collection_recovery_fee',
    'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
    'last_fico_range_high', 'last_fico_range_low',
    'hardship_flag', 'hardship_type', 'hardship_reason', 'hardship_status',
    'deferral_term', 'hardship_amount', 'hardship_start_date', 'hardship_end_date',
    'payment_plan_start_date', 'hardship_length', 'hardship_dpd', 'hardship_loan_status',
    'orig_projected_additional_accrued_interest', 'hardship_payoff_balance_amount',
    'hardship_last_payment_amount',
    'settlement_status', 'settlement_date', 'settlement_amount',
    'settlement_percentage', 'settlement_term',
    'debt_settlement_flag', 'debt_settlement_flag_date',
    'pymnt_plan',
]
print(f'Family B (original classification): {len(family_B_original)} columns')
for c in family_B_original:
    drop_reasons[c] = 'Family B - post-origination (leakage)'
drop_reasons['funded_amnt_inv'] = ('Family B (REVIEW resolved to B) - funded_amnt_inv/funded_amnt ratio '
                                    'rises from 0.235 (2007) to 0.9996 (2015): the value fills in after origination')

for c in ['emp_title', 'title', 'desc', 'zip_code']:
    drop_reasons[c] = 'Family D - free text'

zero_var_cols = ['policy_code', 'disbursement_method', 'pymnt_plan', 'hardship_flag', 'out_prncp', 'out_prncp_inv']
for c in zero_var_cols:
    if c in drop_reasons:
        drop_reasons[c] = drop_reasons[c] + ' + zero variance in the population'
    else:
        drop_reasons[c] = 'Zero variance in the population (cardinality = 1)'

block_dec2015 = ['open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
                  'total_bal_il', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
                  'inq_fi', 'total_cu_tl', 'inq_last_12m']
print(f'Block born Dec/2015: {len(block_dec2015)} columns')
for c in block_dec2015:
    drop_reasons[c] = 'Block born Dec/2015 (~97.8% null in the population, the maturity cutoff ends before the rollout completes)'

null100_cols = ['revol_bal_joint', 'sec_app_fico_range_low', 'sec_app_fico_range_high',
                 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths', 'sec_app_mort_acc',
                 'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il',
                 'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths',
                 'sec_app_collections_12_mths_ex_med', 'sec_app_mths_since_last_major_derog',
                 'next_pymnt_d']
for c in null100_cols:
    if c in drop_reasons:
        drop_reasons[c] = drop_reasons[c] + ' + 100% null in the population'
    else:
        drop_reasons[c] = '100% null in the population (born after the end of the population window, Mar/2017)'

drop_reasons['addr_state'] = ('Rare-category / high cardinality (51 levels, 1/3 without enough sample) - '
                                'dropped by the decision recorded in cleaning_decisions.md')

drop_reasons['emp_length'] = 'Mechanical transformation - replaced by emp_length_anos (parsed)'

print()
print(f'Total columns to drop: {len(drop_reasons)}')
for c, reason in sorted(drop_reasons.items()):
    print(f'  {c}: {reason}')


Family B (original classification): 37 columns
Block born Dec/2015: 13 columns

Total columns to drop: 75
  addr_state: Rare-category / high cardinality (51 levels, 1/3 without enough sample) - dropped by the decision recorded in cleaning_decisions.md
  all_util: Block born Dec/2015 (~97.8% null in the population, the maturity cutoff ends before the rollout completes)
  collection_recovery_fee: Family B - post-origination (leakage)
  debt_settlement_flag: Family B - post-origination (leakage)
  debt_settlement_flag_date: Family B - post-origination (leakage)
  deferral_term: Family B - post-origination (leakage)
  desc: Family D - free text
  disbursement_method: Zero variance in the population (cardinality = 1)
  emp_length: Mechanical transformation - replaced by emp_length_anos (parsed)
  emp_title: Family D - free text
  funded_amnt_inv: Family B (REVIEW resolved to B) - funded_amnt_inv/funded_amnt ratio rises from 0.235 (2007) to 0.9996 (2015): the value fills in after origination

In [7]:
cols_to_drop = [c for c in drop_reasons if c in df.columns]
missing = [c for c in drop_reasons if c not in df.columns]
if missing:
    print(f'WARNING: columns in the drop list that do not exist in the dataframe: {missing}')

shape_before = df.shape
df = df.drop(columns=cols_to_drop)
print(f'Shape before: {shape_before} -> after: {df.shape}')


Shape before: (673548, 153) -> after: (673548, 78)


## 5. Family E (EVAL_ONLY) and provisional exclusions

Family E never enters any feature set, in any phase. int_rate, grade and sub_grade
are kept in the dataset but marked as provisional exclusions (see "Deferred to modeling"
in cleaning_decisions.md) — to be resolved during modeling, with a comparison version.

In [8]:
EVAL_ONLY = ['loan_status', 'loan_amnt', 'installment', 'term', 'total_rec_prncp']
print('EVAL_ONLY (never features, in any phase):', EVAL_ONLY)
print('All present in the dataframe?', all(c in df.columns for c in EVAL_ONLY))

PROVISIONAL_EXCLUDE = ['int_rate', 'grade', 'sub_grade']
print()
print('PROVISIONAL_EXCLUDE (kept in the dataset, excluded from the feature set until the comparative')
print('modeling decides whether they go in):', PROVISIONAL_EXCLUDE)
print('All present in the dataframe?', all(c in df.columns for c in PROVISIONAL_EXCLUDE))


EVAL_ONLY (never features, in any phase): ['loan_status', 'loan_amnt', 'installment', 'term', 'total_rec_prncp']
All present in the dataframe? True

PROVISIONAL_EXCLUDE (kept in the dataset, excluded from the feature set until the comparative
modeling decides whether they go in): ['int_rate', 'grade', 'sub_grade']
All present in the dataframe? True


## 6. MNAR — flag + sentinel 999 (mths_since_*) and -1 (emp_length_anos)

In [9]:
mnar_cols_999 = ['mths_since_last_delinq', 'mths_since_last_record', 'mths_since_recent_bc_dlq',
                  'mths_since_recent_revol_delinq', 'mths_since_last_major_derog']

for c in mnar_cols_999:
    pct_null_before = df[c].isnull().mean() * 100
    flag_col = f'{c}_missing'
    df[flag_col] = df[c].isnull().astype(int)
    df[c] = df[c].fillna(999)
    pct_null_after = df[c].isnull().mean() * 100
    print(f'{c}: %null before={pct_null_before:.2f}% after={pct_null_after:.2f}% | {flag_col} sum={df[flag_col].sum():,}')

print()
pct_null_before = df['emp_length_anos'].isnull().mean() * 100
df['emp_length_missing'] = df['emp_length_anos'].isnull().astype(int)
df['emp_length_anos'] = df['emp_length_anos'].fillna(-1)
pct_null_after = df['emp_length_anos'].isnull().mean() * 100
print(f'emp_length_anos: %null before={pct_null_before:.2f}% after={pct_null_after:.2f}% | '
      f'emp_length_missing sum={df["emp_length_missing"].sum():,}')


mths_since_last_delinq: %null before=51.77% after=0.00% | mths_since_last_delinq_missing sum=348,666
mths_since_last_record: %null before=84.58% after=0.00% | mths_since_last_record_missing sum=569,678
mths_since_recent_bc_dlq: %null before=77.07% after=0.00% | mths_since_recent_bc_dlq_missing sum=519,104
mths_since_recent_revol_delinq: %null before=67.76% after=0.00% | mths_since_recent_revol_delinq_missing sum=456,366
mths_since_last_major_derog: %null before=75.42% after=0.00% | mths_since_last_major_derog_missing sum=508,015

emp_length_anos: %null before=5.58% after=0.00% | emp_length_missing sum=37,567


## 7. Pre-2012 bureau block — era_pre_2012 flag + sentinel -1

Columns identified programmatically by their overlap with the
`tot_cur_bal.isna()` mask (already validated in 02_cleaning.ipynb), not by a fixed list.

In [10]:
ref_mask = df['tot_cur_bal'].isna()
already_handled = set(EVAL_ONLY) | set(mnar_cols_999) | {'emp_length_anos', 'emp_length_missing', 'target'}
candidate_cols = [c for c in df.columns if c not in already_handled and df[c].isnull().sum() > 0]

bureau_2012_cols = []
for c in candidate_cols:
    col_mask = df[c].isna()
    if col_mask.sum() == 0:
        continue
    overlap_of_ref = (col_mask & ref_mask).sum() / ref_mask.sum() * 100 if ref_mask.sum() > 0 else 0
    overlap_of_col = (col_mask & ref_mask).sum() / col_mask.sum() * 100 if col_mask.sum() > 0 else 0
    if overlap_of_ref > 95 and overlap_of_col > 95:
        bureau_2012_cols.append(c)

print(f'Columns of the 2012 bureau block identified via the tot_cur_bal mask: {len(bureau_2012_cols)}')
print(bureau_2012_cols)
print('(note: the contract estimated "~24"; the exact count measured via mask overlap prevails)')


Columns of the 2012 bureau block identified via the tot_cur_bal mask: 21
['tot_coll_amt', 'tot_cur_bal', 'total_rev_hi_lim', 'avg_cur_bal', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'tot_hi_cred_lim', 'total_il_high_credit_limit']
(note: the contract estimated "~24"; the exact count measured via mask overlap prevails)


In [11]:
df['era_pre_2012'] = ref_mask.astype(int)
for c in bureau_2012_cols:
    df[c] = df[c].fillna(-1)

print(f'era_pre_2012 - flag sum: {df["era_pre_2012"].sum():,}')
print(f'%_population with era_pre_2012=1: {df["era_pre_2012"].mean() * 100:.4f}%')
print('Compare with the overlap already measured in 02_cleaning.ipynb (~10.0255% / 67,527 rows).')


era_pre_2012 - flag sum: 67,527
%_population with era_pre_2012=1: 10.0256%
Compare with the overlap already measured in 02_cleaning.ipynb (~10.0255% / 67,527 rows).


## 8. Consolidation of rare categories

In [12]:
print('home_ownership - before:')
print(df['home_ownership'].value_counts())

df['home_ownership'] = df['home_ownership'].replace({'any': 'other', 'none': 'other'})

print()
print('home_ownership - after:')
print(df['home_ownership'].value_counts())


home_ownership - before:
home_ownership
mortgage    320795
rent        285754
own          66808
other          144
none            45
any              2
Name: count, dtype: int64

home_ownership - after:
home_ownership
mortgage    320795
rent        285754
own          66808
other          191
Name: count, dtype: int64


In [13]:
print('purpose - before:')
print(df['purpose'].value_counts())

df['purpose'] = df['purpose'].replace({'wedding': 'other', 'educational': 'other', 'renewable_energy': 'other'})

print()
print('purpose - after:')
print(df['purpose'].value_counts())


purpose - before:
purpose
debt_consolidation    385923
credit_card           159055
home_improvement       39094
other                  36375
major_purchase         14076
small_business          8635
car                     7786
medical                 7245
moving                  4815
vacation                4426
house                   2990
wedding                 2290
renewable_energy         512
educational              326
Name: count, dtype: int64



purpose - after:
purpose
debt_consolidation    385923
credit_card           159055
other                  39503
home_improvement       39094
major_purchase         14076
small_business          8635
car                     7786
medical                 7245
moving                  4815
vacation                4426
house                   2990
Name: count, dtype: int64


## 9. Remaining nulls (no imputation — report only)

In [14]:
remaining_nulls = (df.isnull().mean() * 100)
remaining_nulls = remaining_nulls[remaining_nulls > 0].sort_values(ascending=False)
print(f'Columns with remaining nulls: {len(remaining_nulls)}')
remaining_nulls.to_frame('%_null')


Columns with remaining nulls: 23


,%_null
dti_joint,99.965407
annual_inc_joint,99.965259
verification_status_joint,99.965259
il_util,98.097389
mths_since_recent_inq,16.971025
mo_sin_old_il_acct,13.294821
num_tl_120dpd_2m,13.134476
num_sats,8.290575
num_bc_sats,8.290575
bc_util,7.989631


## 10. Writing the analytical dataset

In [15]:
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

parquet_path = PROCESSED_DIR / 'loans_clean.parquet'
df.to_parquet(parquet_path, index=False)

sample_path = PROCESSED_DIR / 'loans_clean_sample.csv'
df.sample(n=1000, random_state=42).to_csv(sample_path, index=False)

parquet_size_mb = parquet_path.stat().st_size / 1024**2
sample_size_kb = sample_path.stat().st_size / 1024

print(f'Final shape: {df.shape}')
print(f'Parquet: {parquet_path} - {parquet_size_mb:.2f} MB')
print(f'Sample CSV: {sample_path} - {sample_size_kb:.2f} KB')
print(f'Final default rate: {df["target"].mean() * 100:.4f}%')


Final shape: (673548, 85)
Parquet: ..\data\processed\loans_clean.parquet - 45.53 MB
Sample CSV: ..\data\processed\loans_clean_sample.csv - 428.12 KB
Final default rate: 14.8148%


## 11. Final integrity check

In [16]:
family_B_all = family_B_original + ['funded_amnt_inv']
survived_B = [c for c in family_B_all if c in df.columns]
print(f'Surviving family B columns (expected 0): {survived_B}')
assert len(survived_B) == 0, 'STOPPING: family B column(s) survived the drop.'

print()
print('EVAL_ONLY present in the dataframe:', [c for c in EVAL_ONLY if c in df.columns])
print('EVAL_ONLY missing:', [c for c in EVAL_ONLY if c not in df.columns])
print('(EVAL_ONLY exists in the file for the financial-outcome calculation and auditing; the')
print(' exclusion from the feature set belongs to the modeling phase, not to this notebook.)')


Surviving family B columns (expected 0): []

EVAL_ONLY present in the dataframe: ['loan_status', 'loan_amnt', 'installment', 'term', 'total_rec_prncp']
EVAL_ONLY missing: []
(EVAL_ONLY exists in the file for the financial-outcome calculation and auditing; the
 exclusion from the feature set belongs to the modeling phase, not to this notebook.)


In [17]:
id_status = 'id was removed from the dataset (family A - identifier), nothing to check.' if 'id' not in df.columns else str(df['id'].dtype)
print('id:', id_status)
print()
print('final dtypes:')
print(df.dtypes.to_string())


id: id was removed from the dataset (family A - identifier), nothing to check.

final dtypes:
loan_amnt                                        float64
funded_amnt                                      float64
term                                             float64
int_rate                                         float64
installment                                      float64
grade                                                str
sub_grade                                            str
home_ownership                                       str
annual_inc                                       float64
verification_status                                  str
issue_d                                   datetime64[us]
loan_status                                          str
purpose                                              str
dti                                              float64
delinq_2yrs                                      float64
earliest_cr_line                          datetime6

In [18]:
expected_object_cols = {'loan_status', 'grade', 'sub_grade', 'home_ownership', 'verification_status',
                          'purpose', 'initial_list_status', 'application_type', 'verification_status_joint'}
unexpected_object = [c for c in df.columns if df[c].dtype == 'object' and c not in expected_object_cols]
print(f'Unexpected object columns (should be numeric): {unexpected_object}')
if unexpected_object:
    print('WARNING: review before continuing.')
else:
    print('No unexpected object column. All remaining categorical columns are the expected ones.')


Unexpected object columns (should be numeric): []
No unexpected object column. All remaining categorical columns are the expected ones.


## Diagnosis of the remaining nulls

Read-only. No imputation, no removal, no change to the parquet. Loads
`data/processed/loans_clean.parquet` (673,548 rows) directly — it does not re-run the
dataset build.

In [19]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)

df = pd.read_parquet(Path('..') / 'data' / 'processed' / 'loans_clean.parquet')
print(f'Shape loaded: {df.shape}')
assert len(df) == 673548, f'Unexpected N: {len(df)} (expected 673548)'

df['issue_year'] = df['issue_d'].dt.year
print('OK - parquet loaded, it will not be rewritten.')


Shape loaded: (673548, 85)
OK - parquet loaded, it will not be rewritten.


### Part 1 - Mechanism of the 10 columns in the March/2012 cluster

Expected reading: if %null drops to ~0% after 2012, it is a column rollout (structural
temporal missingness). If %null is stable across all vintages, it is structural
missingness by event (the borrower never had the event).

In [20]:
cluster_mar2012 = ['mort_acc', 'total_bc_limit', 'total_bal_ex_mort', 'acc_open_past_24mths',
                    'bc_util', 'bc_open_to_buy', 'percent_bc_gt_75', 'mths_since_recent_bc',
                    'mths_since_recent_inq', 'mo_sin_old_il_acct']

years = list(range(2007, 2016))
rows = []
for c in cluster_mar2012:
    null_mask = df[c].isnull()
    row = {'column': c, '%null_population': round(null_mask.mean() * 100, 4)}
    for y in years:
        year_mask = df['issue_year'] == y
        row[f'%null_{y}'] = round(df.loc[year_mask, c].isnull().mean() * 100, 2)
    null_rate = df.loc[null_mask, 'target'].mean() * 100
    nonnull_rate = df.loc[~null_mask, 'target'].mean() * 100
    row['default_null_%'] = round(null_rate, 2)
    row['default_nonnull_%'] = round(nonnull_rate, 2)
    row['difference_pp'] = round(null_rate - nonnull_rate, 2)
    n_null = int(null_mask.sum())
    overlap = (null_mask & (df['era_pre_2012'] == 1)).sum() / n_null * 100 if n_null > 0 else np.nan
    row['%_overlap_era_pre_2012'] = round(overlap, 2)
    rows.append(row)

cluster_table = pd.DataFrame(rows).set_index('column')
cluster_table


,%null_population,%null_2007,%null_2008,%null_2009,%null_2010,%null_2011,%null_2012,%null_2013,%null_2014,%null_2015,default_null_%,default_nonnull_%,difference_pp,%_overlap_era_pre_2012
column,,,,,,,,,,,,,,
mort_acc,7.0197,100.0,100.0,100.0,100.0,100.0,14.04,0.00,0.00,0.00,14.56,14.83,-0.27,100.00
total_bc_limit,7.0197,100.0,100.0,100.0,100.0,100.0,14.04,0.00,0.00,0.00,14.56,14.83,-0.27,100.00
total_bal_ex_mort,7.0197,100.0,100.0,100.0,100.0,100.0,14.04,0.00,0.00,0.00,14.56,14.83,-0.27,100.00
acc_open_past_24mths,7.0197,100.0,100.0,100.0,100.0,100.0,14.04,0.00,0.00,0.00,14.56,14.83,-0.27,100.00
bc_util,7.9896,100.0,100.0,100.0,100.0,100.0,15.08,0.79,1.16,1.07,14.85,14.81,0.04,88.39
bc_open_to_buy,7.9286,100.0,100.0,100.0,100.0,100.0,15.03,0.75,1.08,1.00,14.83,14.81,0.01,89.04
percent_bc_gt_75,7.9813,100.0,100.0,100.0,100.0,100.0,15.03,0.75,1.14,1.09,14.84,14.81,0.02,88.46
mths_since_recent_bc,7.8612,100.0,100.0,100.0,100.0,100.0,14.89,0.65,0.99,0.96,14.81,14.82,-0.01,89.75
mths_since_recent_inq,16.9710,100.0,100.0,100.0,100.0,100.0,24.90,10.82,9.48,11.04,12.11,15.37,-3.25,43.69


### Part 2 - Grouping by identical mask

In [21]:
mask_signatures = {}
for c in cluster_mar2012:
    sig = df[c].isnull().values.tobytes()
    mask_signatures.setdefault(sig, []).append(c)

groups = list(mask_signatures.values())
print(f'Groups with EXACTLY identical masks found: {len(groups)}')
for g in groups:
    pct_null = df[g[0]].isnull().mean() * 100
    print(f'  Group (size {len(g)}): {g} | %null = {pct_null:.4f}%')


Groups with EXACTLY identical masks found: 7
  Group (size 4): ['mort_acc', 'total_bc_limit', 'total_bal_ex_mort', 'acc_open_past_24mths'] | %null = 7.0197%
  Group (size 1): ['bc_util'] | %null = 7.9896%
  Group (size 1): ['bc_open_to_buy'] | %null = 7.9286%
  Group (size 1): ['percent_bc_gt_75'] | %null = 7.9813%
  Group (size 1): ['mths_since_recent_bc'] | %null = 7.8612%
  Group (size 1): ['mths_since_recent_inq'] | %null = 16.9710%
  Group (size 1): ['mo_sin_old_il_acct'] | %null = 13.2948%


In [22]:
masks = {c: df[c].isnull() for c in cluster_mar2012}
overlap_matrix = pd.DataFrame(index=cluster_mar2012, columns=cluster_mar2012, dtype=float)

for c1 in cluster_mar2012:
    for c2 in cluster_mar2012:
        n1 = masks[c1].sum()
        n2 = masks[c2].sum()
        inter = (masks[c1] & masks[c2]).sum()
        denom = min(n1, n2)
        overlap_matrix.loc[c1, c2] = round(inter / denom * 100, 2) if denom > 0 else np.nan

print('Pairwise overlap matrix (% of the SMALLER mask contained in the mask of the crossed column):')
overlap_matrix


Pairwise overlap matrix (% of the SMALLER mask contained in the mask of the crossed column):


,mort_acc,total_bc_limit,total_bal_ex_mort,acc_open_past_24mths,bc_util,bc_open_to_buy,percent_bc_gt_75,mths_since_recent_bc,mths_since_recent_inq,mo_sin_old_il_acct
mort_acc,100.0,100.0,100.0,100.0,100.00,100.00,100.00,100.00,100.00,100.00
total_bc_limit,100.0,100.0,100.0,100.0,100.00,100.00,100.00,100.00,100.00,100.00
total_bal_ex_mort,100.0,100.0,100.0,100.0,100.00,100.00,100.00,100.00,100.00,100.00
acc_open_past_24mths,100.0,100.0,100.0,100.0,100.00,100.00,100.00,100.00,100.00,100.00
bc_util,100.0,100.0,100.0,100.0,100.00,100.00,99.34,99.85,89.54,88.62
bc_open_to_buy,100.0,100.0,100.0,100.0,100.00,100.00,100.00,99.85,90.14,89.25
percent_bc_gt_75,100.0,100.0,100.0,100.0,99.34,100.00,100.00,100.00,89.57,88.67
mths_since_recent_bc,100.0,100.0,100.0,100.0,99.85,99.85,100.00,100.00,90.82,89.95
mths_since_recent_inq,100.0,100.0,100.0,100.0,89.54,90.14,89.57,90.82,100.00,60.73
mo_sin_old_il_acct,100.0,100.0,100.0,100.0,88.62,89.25,88.67,89.95,60.73,100.00


### Part 3 - Sparse nulls (residual group)

pub_rec_bankruptcies, revol_util, chargeoff_within_12_mths, collections_12_mths_ex_med,
tax_liens, dti.

In [23]:
sparse_cols = ['pub_rec_bankruptcies', 'revol_util', 'chargeoff_within_12_mths',
               'collections_12_mths_ex_med', 'tax_liens', 'dti']

any_null_mask = df[sparse_cols].isnull().any(axis=1)
n_unique_rows = int(any_null_mask.sum())
print(f'Unique rows with a null in at least one of the 6 columns: {n_unique_rows}')

default_rate_subset = df.loc[any_null_mask, 'target'].mean() * 100
default_rate_pop = df['target'].mean() * 100
print(f'Default rate in this subset: {default_rate_subset:.4f}%')
print(f'Default rate of the whole population: {default_rate_pop:.4f}%')
print(f'Difference: {default_rate_subset - default_rate_pop:.4f} pp')


Unique rows with a null in at least one of the 6 columns: 1079
Default rate in this subset: 18.3503%
Default rate of the whole population: 14.8148%
Difference: 3.5355 pp


In [24]:
dist_by_year = df.loc[any_null_mask, 'issue_year'].value_counts().sort_index()
dist_by_year_pct = (dist_by_year / dist_by_year.sum() * 100).round(2)
print('Distribution of these rows by issue_d year (count and % of the subset):')
pd.DataFrame({'n_rows': dist_by_year, '%_of_subset': dist_by_year_pct})


Distribution of these rows by issue_d year (count and % of the subset):


,n_rows,%_of_subset
issue_year,,
2007,246,22.80
2008,458,42.45
2009,17,1.58
2010,19,1.76
2011,9,0.83
2012,47,4.36
2013,78,7.23
2014,77,7.14
2015,128,11.86


In [25]:
example_cols = ['issue_d', 'term', 'loan_amnt', 'annual_inc', 'emp_length_anos',
                 'era_pre_2012', 'loan_status'] + sparse_cols
examples = df.loc[any_null_mask, example_cols].sample(n=10, random_state=42)
examples


,issue_d,term,loan_amnt,annual_inc,emp_length_anos,era_pre_2012,loan_status,pub_rec_bankruptcies,revol_util,chargeoff_within_12_mths,collections_12_mths_ex_med,tax_liens,dti
484829,2008-02-01,36.0,3975.0,24000.0,2.0,1,Fully Paid,NaN,82.3,0.0,0.0,0.0,21.90
484960,2008-01-01,36.0,4000.0,65000.0,10.0,1,Fully Paid,NaN,5.3,0.0,0.0,0.0,9.25
485149,2007-12-01,36.0,12000.0,105000.0,0.0,1,Fully Paid,NaN,53.8,0.0,0.0,0.0,18.25
485000,2008-01-01,36.0,20000.0,57860.0,1.0,1,Fully Paid,NaN,70.0,0.0,0.0,0.0,10.14
485252,2007-10-01,36.0,7000.0,55400.0,2.0,1,Fully Paid,NaN,33.8,0.0,0.0,0.0,10.05
485031,2008-01-01,36.0,10000.0,55000.0,0.0,1,Fully Paid,NaN,20.4,0.0,0.0,0.0,7.59
542287,2013-09-01,36.0,14000.0,122000.0,10.0,0,Fully Paid,0.0,NaN,0.0,0.0,0.0,7.88
545034,2013-08-01,60.0,11200.0,65000.0,10.0,0,Fully Paid,0.0,NaN,0.0,0.0,0.0,10.13
485373,2007-07-01,36.0,8500.0,18000.0,3.0,1,Fully Paid,NaN,26.9,NaN,NaN,NaN,6.40
558082,2013-07-01,36.0,15000.0,64000.0,9.0,0,Fully Paid,0.0,NaN,0.0,0.0,0.0,15.62


### Part 4 - Confirmation of the drop group

In [26]:
il_util_by_year = df.groupby('issue_year')['il_util'].apply(lambda s: s.isnull().mean() * 100).round(2)
print('il_util - %null per issue_d year (population, 2007-2015):')
print(il_util_by_year)
print()
print('The Dec/2015 block already dropped (e.g. open_acc_6m) had the same pattern within the population:')
print('100% null up to 2014, falling to ~94.9% in 2015 (late rollout, see 02_cleaning.ipynb).')


il_util - %null per issue_d year (population, 2007-2015):
issue_year
2007    100.00
2008    100.00
2009    100.00
2010    100.00
2011    100.00
2012    100.00
2013    100.00
2014    100.00
2015     95.47
Name: il_util, dtype: float64

The Dec/2015 block already dropped (e.g. open_acc_6m) had the same pattern within the population:
100% null up to 2014, falling to ~94.9% in 2015 (late rollout, see 02_cleaning.ipynb).


In [27]:
joint_cols = ['dti_joint', 'annual_inc_joint', 'verification_status_joint']
joint_app_mask = df['application_type'] == 'joint app'
print(f'Rows with application_type == "joint app": {int(joint_app_mask.sum())}')
print()

for c in joint_cols:
    non_null_mask = df[c].notna()
    match = (non_null_mask == joint_app_mask).all()
    n_non_null = int(non_null_mask.sum())
    print(f'{c}: non-null rows={n_non_null} | mask identical to application_type==joint app? {match}')


Rows with application_type == "joint app": 234

dti_joint: non-null rows=233 | mask identical to application_type==joint app? False
annual_inc_joint: non-null rows=234 | mask identical to application_type==joint app? True
verification_status_joint: non-null rows=234 | mask identical to application_type==joint app? True


## Finalization - treatment of the remaining nulls

Implements docs/cleaning_decisions.md ("Remaining nulls - resolved by mechanism"). If anything
here diverges from the document, the notebook stops (assert) and flags it. Reloads the parquet from
scratch (does not depend on the state of the diagnosis section above).

In [28]:
df = pd.read_parquet(Path('..') / 'data' / 'processed' / 'loans_clean.parquet')
print(f'Shape reloaded: {df.shape}')
assert len(df) == 673548, f'Unexpected N: {len(df)} (expected 673548)'


Shape reloaded: (673548, 85)


## 1. Removal of the joint app rows (systematically distorted dti)

In [29]:
n_before = len(df)
joint_mask = df['application_type'] == 'joint app'
n_joint = int(joint_mask.sum())
print(f'Joint app rows found: {n_joint} (expected: 234)')
assert n_joint == 234, f'STOPPING: expected 234 joint app rows, found {n_joint} - diverges from the contract.'

df = df.loc[~joint_mask].reset_index(drop=True)
print(f'N before: {n_before:,} -> N after: {len(df):,}')


Joint app rows found: 234 (expected: 234)


N before: 673,548 -> N after: 673,314


## 2. Dropping the Mechanism 4 columns (collection window)

In [30]:
drop_reasons_2 = {
    'il_util': ('Mechanism 4 - same late rollout (Dec/2015) as the 13-column block already dropped; '
                '100% null up to 2014, 95.47% in 2015. Left out of scope by oversight, not by criterion.'),
    'dti_joint': 'Mechanism 4 - only exists for joint app, which was just removed from the dataset.',
    'annual_inc_joint': 'Mechanism 4 - only exists for joint app, which was just removed from the dataset.',
    'verification_status_joint': 'Mechanism 4 - only exists for joint app, which was just removed from the dataset.',
}
print('Columns to drop in this step:')
for c, r in drop_reasons_2.items():
    print(f'  {c}: {r}')

shape_before = df.shape
df = df.drop(columns=list(drop_reasons_2.keys()))
print(f'Shape before: {shape_before} -> after: {df.shape}')


Columns to drop in this step:
  il_util: Mechanism 4 - same late rollout (Dec/2015) as the 13-column block already dropped; 100% null up to 2014, 95.47% in 2015. Left out of scope by oversight, not by criterion.
  dti_joint: Mechanism 4 - only exists for joint app, which was just removed from the dataset.
  annual_inc_joint: Mechanism 4 - only exists for joint app, which was just removed from the dataset.
  verification_status_joint: Mechanism 4 - only exists for joint app, which was just removed from the dataset.
Shape before: (673314, 85) -> after: (673314, 81)


## 3. Mechanism 1 - sentinel -1, no new flag (6 columns)

mort_acc, total_bc_limit, total_bal_ex_mort, acc_open_past_24mths (rollout Mar/2012,
mask identical to each other) plus num_bc_sats and num_sats (rollout Jun/2012, own mask,
but same mechanism). Confirms 100% overlap with era_pre_2012=1 before filling each
one — the assert is on the overlap with the flag, not on mask equality between columns.
If any of them is not 100%, it stops.

In [31]:
mech1_cols = ['mort_acc', 'total_bc_limit', 'total_bal_ex_mort', 'acc_open_past_24mths',
              'num_bc_sats', 'num_sats']

for c in mech1_cols:
    null_mask = df[c].isnull()
    n_null = int(null_mask.sum())
    overlap = (null_mask & (df['era_pre_2012'] == 1)).sum() / n_null * 100 if n_null > 0 else np.nan
    print(f'{c}: nulls={n_null:,} | overlap with era_pre_2012=1: {overlap:.4f}%')
    assert overlap == 100.0, f'STOPPING: {c} has {overlap:.4f}% overlap with era_pre_2012, expected 100% - diverges from the contract.'

for c in mech1_cols:
    df[c] = df[c].fillna(-1)
print()
print('Filled with sentinel -1 (no new flag - already covered by era_pre_2012).')


mort_acc: nulls=47,281 | overlap with era_pre_2012=1: 100.0000%
total_bc_limit: nulls=47,281 | overlap with era_pre_2012=1: 100.0000%
total_bal_ex_mort: nulls=47,281 | overlap with era_pre_2012=1: 100.0000%
acc_open_past_24mths: nulls=47,281 | overlap with era_pre_2012=1: 100.0000%
num_bc_sats: nulls=55,841 | overlap with era_pre_2012=1: 100.0000%
num_sats: nulls=55,841 | overlap with era_pre_2012=1: 100.0000%

Filled with sentinel -1 (no new flag - already covered by era_pre_2012).


## 4. Mechanism 2 - sentinel 999 (6 mixed-cause columns) + flag for mths_since_recent_inq

In [32]:
mech2_cols = ['bc_util', 'bc_open_to_buy', 'percent_bc_gt_75', 'mths_since_recent_bc',
              'mo_sin_old_il_acct', 'mths_since_recent_inq']

df['mths_since_recent_inq_missing'] = df['mths_since_recent_inq'].isnull().astype(int)

for c in mech2_cols:
    pct_null_before = df[c].isnull().mean() * 100
    n_null_before = int(df[c].isnull().sum())
    df[c] = df[c].fillna(999)
    print(f'{c}: %null before={pct_null_before:.4f}% | rows filled with 999={n_null_before:,}')

print()
print(f'Flag mths_since_recent_inq_missing - sum: {df["mths_since_recent_inq_missing"].sum():,}')


bc_util: %null before=7.9918% | rows filled with 999=53,810
bc_open_to_buy: %null before=7.9308% | rows filled with 999=53,399
percent_bc_gt_75: %null before=7.9835% | rows filled with 999=53,754
mths_since_recent_bc: %null before=7.8635% | rows filled with 999=52,946
mo_sin_old_il_acct: %null before=13.2990% | rows filled with 999=89,544
mths_since_recent_inq: %null before=16.9741% | rows filled with 999=114,289

Flag mths_since_recent_inq_missing - sum: 114,289


## 4b. num_tl_120dpd_2m - sentinel -1 + its own flag

Mechanism 2, but with the opposite sign of mths_since_recent_inq: here missingness is missing
recent bureau information (correlates with risk), not absence of an event (which
correlates with safety). It is a count, not a "months since"; there is no
"higher=safer" order to preserve, so the sentinel is -1 (not 999).

In [33]:
pct_null_before = df['num_tl_120dpd_2m'].isnull().mean() * 100
n_null_before = int(df['num_tl_120dpd_2m'].isnull().sum())

df['num_tl_120dpd_2m_missing'] = df['num_tl_120dpd_2m'].isnull().astype(int)
default_rate_flag = df.loc[df['num_tl_120dpd_2m_missing'] == 1, 'target'].mean() * 100

df['num_tl_120dpd_2m'] = df['num_tl_120dpd_2m'].fillna(-1)

print(f'num_tl_120dpd_2m: %null before={pct_null_before:.4f}% | rows filled with -1={n_null_before:,}')
print(f'Flag num_tl_120dpd_2m_missing - sum: {df["num_tl_120dpd_2m_missing"].sum():,}')
print(f'Default rate within the flag: {default_rate_flag:.4f}%')


num_tl_120dpd_2m: %null before=13.1390% | rows filled with -1=88,467
Flag num_tl_120dpd_2m_missing - sum: 88,467
Default rate within the flag: 15.8172%


## 5. Mechanism 3 - aggregate flag + median (6 sparse-null columns)

In [34]:
sparse_cols = ['pub_rec_bankruptcies', 'revol_util', 'chargeoff_within_12_mths',
               'collections_12_mths_ex_med', 'tax_liens', 'dti']

any_null_mask = df[sparse_cols].isnull().any(axis=1)
n_sparse = int(any_null_mask.sum())
df['sparse_bureau_missing'] = any_null_mask.astype(int)
print(f'sparse_bureau_missing - sum: {n_sparse:,} (expected close to 1,079, lower because of the joint app removal)')

default_rate_sparse = df.loc[any_null_mask, 'target'].mean() * 100
print(f'Default rate within the sparse_bureau_missing flag: {default_rate_sparse:.4f}%')
print()

for c in sparse_cols:
    median_val = df[c].median()
    n_null = int(df[c].isnull().sum())
    df[c] = df[c].fillna(median_val)
    print(f'{c}: median used={median_val} | rows imputed={n_null:,}')


sparse_bureau_missing - sum: 1,077 (expected close to 1,079, lower because of the joint app removal)
Default rate within the sparse_bureau_missing flag: 18.2916%

pub_rec_bankruptcies: median used=0.0 | rows imputed=697
revol_util: median used=55.0 | rows imputed=378
chargeoff_within_12_mths: median used=0.0 | rows imputed=56
collections_12_mths_ex_med: median used=0.0 | rows imputed=56
tax_liens: median used=0.0 | rows imputed=39
dti: median used=17.06 | rows imputed=0


## 6. Final integrity check

In [35]:
remaining_nulls = df.isnull().sum()
remaining_nulls = remaining_nulls[remaining_nulls > 0]
print(f'Columns with remaining nulls: {len(remaining_nulls)}')
if len(remaining_nulls) > 0:
    print(remaining_nulls)
assert len(remaining_nulls) == 0, 'STOPPING: there are still nulls in the dataset.'
print('No remaining nulls. OK.')


Columns with remaining nulls: 0
No remaining nulls. OK.


In [36]:
family_B_all = family_B_original + ['funded_amnt_inv']
survived_B = [c for c in family_B_all if c in df.columns]
print(f'Surviving family B columns (expected 0): {survived_B}')
assert len(survived_B) == 0, 'STOPPING: family B column(s) survived.'

print()
eval_only_present = [c for c in EVAL_ONLY if c in df.columns]
print('EVAL_ONLY present:', eval_only_present)
assert eval_only_present == EVAL_ONLY, 'STOPPING: EVAL_ONLY incomplete.'

print()
provisional_present = [c for c in PROVISIONAL_EXCLUDE if c in df.columns]
print('PROVISIONAL_EXCLUDE present:', provisional_present)
assert provisional_present == PROVISIONAL_EXCLUDE, 'STOPPING: PROVISIONAL_EXCLUDE incomplete.'


Surviving family B columns (expected 0): []

EVAL_ONLY present: ['loan_status', 'loan_amnt', 'installment', 'term', 'total_rec_prncp']

PROVISIONAL_EXCLUDE present: ['int_rate', 'grade', 'sub_grade']


In [37]:
expected_object_cols = {'loan_status', 'grade', 'sub_grade', 'home_ownership', 'verification_status',
                          'purpose', 'initial_list_status', 'application_type'}
unexpected_object = [c for c in df.columns if df[c].dtype == 'object' and c not in expected_object_cols]
print(f'Unexpected object columns: {unexpected_object}')
if unexpected_object:
    print('WARNING: review before continuing.')
else:
    print('No unexpected object column.')

print()
print('final dtypes:')
print(df.dtypes.to_string())


Unexpected object columns: []
No unexpected object column.

final dtypes:
loan_amnt                                        float64
funded_amnt                                      float64
term                                             float64
int_rate                                         float64
installment                                      float64
grade                                                str
sub_grade                                            str
home_ownership                                       str
annual_inc                                       float64
verification_status                                  str
issue_d                                   datetime64[us]
loan_status                                          str
purpose                                              str
dti                                              float64
delinq_2yrs                                      float64
earliest_cr_line                          datetime64[us]
fico_range_low

In [38]:
engineered_flags = ['target', 'era_pre_2012',
                     'mths_since_last_delinq_missing', 'mths_since_last_record_missing',
                     'mths_since_recent_bc_dlq_missing', 'mths_since_recent_revol_delinq_missing',
                     'mths_since_last_major_derog_missing', 'emp_length_missing',
                     'mths_since_recent_inq_missing', 'num_tl_120dpd_2m_missing', 'sparse_bureau_missing']

groups = {
    'EVAL_ONLY': [c for c in EVAL_ONLY if c in df.columns],
    'PROVISIONAL_EXCLUDE': [c for c in PROVISIONAL_EXCLUDE if c in df.columns],
    'Engineered (target/flags/sentinels)': [c for c in engineered_flags if c in df.columns],
}
already_grouped = set(sum(groups.values(), []))
groups['Feature candidates (family C)'] = [c for c in df.columns if c not in already_grouped]

for g, cols in groups.items():
    print(f'\n{g} ({len(cols)}):')
    print(cols)

print()
print(f'Final shape: {df.shape}')
print(f'Final default rate: {df["target"].mean() * 100:.4f}%')



EVAL_ONLY (5):
['loan_status', 'loan_amnt', 'installment', 'term', 'total_rec_prncp']

PROVISIONAL_EXCLUDE (3):
['int_rate', 'grade', 'sub_grade']

Engineered (target/flags/sentinels) (11):
['target', 'era_pre_2012', 'mths_since_last_delinq_missing', 'mths_since_last_record_missing', 'mths_since_recent_bc_dlq_missing', 'mths_since_recent_revol_delinq_missing', 'mths_since_last_major_derog_missing', 'emp_length_missing', 'mths_since_recent_inq_missing', 'num_tl_120dpd_2m_missing', 'sparse_bureau_missing']

Feature candidates (family C) (65):
['funded_amnt', 'home_ownership', 'annual_inc', 'verification_status', 'issue_d', 'purpose', 'dti', 'delinq_2yrs', 'earliest_cr_line', 'fico_range_low', 'fico_range_high', 'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc', 'initial_list_status', 'collections_12_mths_ex_med', 'mths_since_last_major_derog', 'application_type', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_

## 7. Overwriting the analytical dataset

In [39]:
parquet_path = PROCESSED_DIR / 'loans_clean.parquet'
df.to_parquet(parquet_path, index=False)

sample_path = PROCESSED_DIR / 'loans_clean_sample.csv'
df.sample(n=1000, random_state=42).to_csv(sample_path, index=False)

print(f'Parquet: {parquet_path} - {parquet_path.stat().st_size / 1024**2:.2f} MB')
print(f'Sample CSV: {sample_path} - {sample_path.stat().st_size / 1024:.2f} KB')


Parquet: ..\data\processed\loans_clean.parquet - 45.52 MB
Sample CSV: ..\data\processed\loans_clean_sample.csv - 435.02 KB
